Repository datapartnership/datapartnership.github.io, pull requests merged in 2023-04, with the labels that each got.

#173 Add Impact Story For Reduced Exposure to COVID-19, the Quality of Your Internet Matters
  content/authors/niccolo-comini/_index.md
  content/authors/nicola-perra/_index.md
  content/authors/nicolo-gozzi/_index.md
  content/updates/covid19-internet-speed-impact.md
  static/images/updates/covid19-internet-speed-impact/covid19-internet-speed-impact-figure1.png
  static/images/updates/covid19-internet-speed-impact/covid19-internet-speed-impact-figure2.png
Labels: post

#185 Update partnership-day-2023.md
  content/updates/partnership-day-2023/index.md
Labels: partnershipday

#187 Remove Forestry.io
  .forestry/front_matter/templates/blog.yml
  .forestry/front_matter/templates/datapartner.yml
  .forestry/settings.yml
  .hugo_build.lock
  CONTRIBUTING.md
  README.md
Labels: bug
